routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CardController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\OrganizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::prefix('admin')->middleware(['auth', 'verified'])->group(function () {

    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::resource('organization', OrganizationController::class);
    Route::resource('board', BoardController::class)->except('create');
    Route::resource('form', FormController::class);
    Route::resource('list', ListController::class)->except('create');

    Route::get('/board/{id}/create', [BoardController::class, 'create'])->name('board.create');

    Route::get('/list/{id}/create', [ListController::class, 'create'])->name('list.create');

    Route::get('/card/{id}/create', [CardController::class, 'create'])->name('card.create');

    Route::post('/card',[CardController::class,'store'])->name('card.store');
});

app/Http/Controllers/BoardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Board;
use App\Models\Form;
use GuzzleHttp\Client;
use Illuminate\Http\Request;

class BoardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('board.create',compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = $request->id;
        $form = Form::first();

        $queries= http_build_query([
            'name' => $request->name,
            'desc' =>$request->description,
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/boards/?" . $queries;

        $client->request('POST', $url, [
            'verify'  => false,
        ]);

        return redirect()->route('organization.show',$id)->with('success','Board created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $form = Form::first();

        $queries= http_build_query([
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/boards/" .$id. "/lists?" . $queries;

        $response = $client->request('GET', $url, [
            'verify'  => false,
        ]);

        // dd($url);

        $responseBody = json_decode($response->getBody());
        // dd($responseBody);

        return view('board.show', compact('responseBody','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $form = Form::first();

        $queries= http_build_query([
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/boards/" .$id. "?" . $queries;
        // dd($url);

        $response = $client->request('GET', $url, [
            'verify'  => false,
        ]);

        $board = json_decode($response->getBody());

        return view('board.edit', compact('board'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {
        $form = Form::first();

        $queries= http_build_query([
            'name' => $request->name,
            'desc' =>$request->description,
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $updateUrl = "https://api.trello.com/1/boards/" .$id. "?" . $queries;
        // dd($updateUrl);

        $client->request('PUT', $updateUrl, [
            'verify'  => false,
        ]);

        return back()->with('success','Board updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Board  $board
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $form = Form::first();

        $queries= http_build_query([
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/boards/".$id."?" . $queries;

        $response = $client->request('DELETE', $url, [
            'verify'  => false,
        ]);

        return back();
    }
}

resources/views/board/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
  <form action="{{ route('board.store') }}" method="post">
    @csrf
    <div class="form-group">
      <label for="name">Board Name</label>
      <input type="text" class="form-control" name="name" id="name" placeholder="Enter board name" required>
    </div>
    <div class="form-group">
      <label for="description">Description</label>
      <input type="text" class="form-control" name="description" id="description" placeholder="Description" required>
    </div>
    <input type="hidden" name="id" value={{$id}}>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
@endsection

resources/views/board/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <form class="form" id="kt_form" method="post" action="{{ route('board.update', $board->id) }}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Board Name</label>
            <input type="text" class="form-control" value="{{ old('name', $board->name) }}" name="name" id="name"
                placeholder="Enter board name" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" value="{{ old('description', $board->desc) }}" name="description" id="description" placeholder="Description"
                required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>




@endsection

resources/views/board/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Boards in this organization</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a type="button" class="btn btn-primary" href="{{route('board.create',$id)}}">Create New Board</a>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($responseBody as $board)
                                        <tr>

                                            <td>
                                                {{ $board->name }}
                                            </td>
                                            <td nowrap="nowrap">

                                                    <a href="{{ route('board.show', $board->id) }}" class="btn btn-icon btn-light btn-hover-primary btn-sm mr-2">
                                                        <i class="fas fa-eye"></i> <input type="hidden" value="{{$id}}">
                                                    </a>

                                                    <a href="{{ route('board.edit', $board->id) }}" class="btn btn-icon btn-light btn-hover-primary btn-sm mr-2">
                                                        <i class="fas fa-edit"></i>
                                                    </a>

                                                    <form method="post" action="{{ route('board.destroy', $board->id) }}" class="d-inline-block">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-icon btn-light btn-hover-primary btn-sm">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/board/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Board Lists</div>


                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a type="button" class="btn btn-primary" href="{{route('list.create',$id)}}">Create New List</a>
                    <div class="card-body">
                        <div class="table-responsive">
                            <ul class="list-group">
                                @foreach ($responseBody as $lists)
                                <a href="{{route('list.show',$id=$lists->id)}}">
                                    <li class="list-group-item">{{$lists->name}}</li>
                                </a>
                                @endforeach
                              </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection