routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CardController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\OrganizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::prefix('admin')->middleware(['auth', 'verified'])->group(function () {

    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::resource('organization', OrganizationController::class);
    Route::resource('board', BoardController::class)->except('create');
    Route::resource('form', FormController::class);
    Route::resource('list', ListController::class)->except('create');

    Route::get('/board/{id}/create', [BoardController::class, 'create'])->name('board.create');

    Route::get('/list/{id}/create', [ListController::class, 'create'])->name('list.create');

    Route::get('/card/{id}/create', [CardController::class, 'create'])->name('card.create');

    Route::post('/card',[CardController::class,'store'])->name('card.store');
});

app/Http/Controllers/ListController.php
<?php

namespace App\Http\Controllers;

use App\Models\Form;
use GuzzleHttp\Client;
use Illuminate\Http\Request;

class ListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        // dd($id);
        return view('list.create',compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = $request->id;
        $form = Form::first();

        $queries= http_build_query([
            'name' => $request->name,
            'idBoard' => $id,
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/lists?" . $queries;
        // dd($url);

        $client->request('POST', $url, [
            'verify'  => false,
        ]);

        return redirect()->route('board.show',$id)->with('success','List created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $form = Form::first();

        $queries= http_build_query([
            'oauth_consumer_key' => $form->consumer_key,
            'oauth_token' => $form->token
        ]);

        $client = new Client();
        $url = "https://api.trello.com/1/lists/" .$id. "/cards?" . $queries;

        $response = $client->request('GET', $url, [
            'verify'  => false,
        ]);

        // dd($url);

        $responseBody = json_decode($response->getBody());
        // dd($responseBody);

        return view('list.show',compact('responseBody','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/list/create.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
    <h1>Board Lists</h1>
  <form action="{{ route('list.store') }}" method="post">
    @csrf
    <div class="form-group">
      <label for="name">List Name</label>
      <input type="text" class="form-control" name="name" id="name" placeholder="Enter list name" required>
    </div>
    <input type="hidden" name="id" value={{$id}}>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
@endsection

resources/views/list/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Board Lists</div>


                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a type="button" class="btn btn-primary" href="{{route('card.create',$id)}}">Create New Card</a>
                    <div class="card-body">
                        <div class="table-responsive">
                            <ul class="list-group">
                                @foreach ($responseBody as $cards)
                                    <li class="list-group-item">{{$cards->name}}</li>
                                @endforeach
                              </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection