routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CardController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListController;
use App\Http\Controllers\BoardController;
use App\Http\Controllers\OrganizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::prefix('admin')->middleware(['auth', 'verified'])->group(function () {

    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::resource('organization', OrganizationController::class);
    Route::resource('board', BoardController::class)->except('create');
    Route::resource('form', FormController::class);
    Route::resource('list', ListController::class)->except('create');

    Route::get('/board/{id}/create', [BoardController::class, 'create'])->name('board.create');

    Route::get('/list/{id}/create', [ListController::class, 'create'])->name('list.create');

    Route::get('/card/{id}/create', [CardController::class, 'create'])->name('card.create');

    Route::post('/card',[CardController::class,'store'])->name('card.store');
});

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Models\Form;
use Illuminate\Http\Request;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('form.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $validated = $request->validate([
            'consumer_key' => ['required', 'string'],
        ]);

        $form=Form::create($validated);

        return redirect()->route('form.edit',$form->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function show(Form $form)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $form=Form::findOrFail($id);
        return view('form.createToken',compact(['id','form']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form=Form::findOrFail($id);
        $validated = $request->validate([
            'token'   => ['required', 'string']
        ]);
        $form->update($validated);
        return redirect()->route('organization.index')->with('success','Item created successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function destroy(Form $form)
    {
        //
    }
}

resources/views/form/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{ route('form.store') }}" method="post">
        @csrf

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        <div class="form-group">
            <label for="consumer_key">Consumer Key</label>
            <div class="row">
                <div class="col-md-4">

                    <input type="text" class="form-control" name="consumer_key" id="consumer_key"
                        placeholder="Enter consumer key" required>
                </div>
                <div class="col-md-4">
                    <a href="https://trello.com/app-key"  target="_blank">Get Your Api Key</a>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/form/createToken.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <form class="form" id="kt_form" method="post" action="{{ route('form.update', $form->id) }}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="token">Token</label>
            <div class="row">
                <div class="col-md-4">
                    <input type="text" class="form-control" name="token" id="token" placeholder="Token" required>
                </div>
                <div class="col-md-4">
                    <a href="https://trello.com/app-key" target="_blank">Get token</a>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection